### PR TITLE
PN5180 support

### PR DESCRIPTION
**Pull request by CrazyRedMachine**
added support for a PN5180 nfc reader. Tested working with Pop'n Music

### CODE REVIEW

**Comment by obeer** [comment]
Hi,
Not certain if I can ask a question about PN 5180 here. I want to get the UID code from a tag to an LCD (16x2). I have it on a monitor (Arduino) but can't get it in a string to read on the LCD display. Any thoughts?

**Comment by obeer** [comment]
the code is:
void loop() {
  nfc.reset();
  nfc.setupRF();
  uint8_t uid[8];

  ISO15693ErrorCode rc = nfc.getInventory(uid);// Try to read a tag ID
  if (rc == ISO15693_EC_OK) { // If the result code was that a card had been read
    lcd1.home();
    lcd1.print(F("UID = "));
    if (rc >= 0) {
      Serial.print(F("UID = "));
      for (int i = 0; i < 8; i++) {
        Serial.print(uid[7 - i], HEX); // LSB is first
        Serial.print(" ");
        lcd1.setCursor(i, 1);
        lcd1.print (uid[7-i],HEX);
last line causing a problem: (no matching function for call to 'LCDIC2::print(uint8_t&, int)').

**Comment by Nadeflore** [comment]
Thanks for adding the support of an affordable nfc reader.
I haven't tested it. but everything looks fine. I'll merge it

**Comment by CrazyRedMachine** [comment]
welcome, I'll monitor issues in case there is trouble with pn5180. thanks for ACreal_IO :)

**Pull request merged**
